db:
  username: ${user.name:postgres}
  password: postgres
  driver: PostgresDriver
  url: postgres:5454
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 234
    third: thirdproperty
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring:
  profiles:
    active: qa
  application:
    name: SpringRunner
  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    ru.radion.database.connectionPool.ConnectionPool: info
  file:
    name: ${logging.file.path}/my-app.log
    path: './logs/${spring.application.name}'
